config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  authenticated :user do
    root 'posts#index', as: :authenticated_root

    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, inverse_of: :posts

  validates :content, presence: :true
  validates :content, length: { minimum: 2, maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_many :posts, inverse_of: :user, dependent: :destroy

  validates :name, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(self.email.downcase)
    "http://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include InertiaJson

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/concerns/inertia_json.rb
module InertiaJson
  extend ActiveSupport::Concern

  def jbuilder(&block)
    JbuilderTemplate.new(view_context, &block).attributes!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render inertia: 'Home', props: {}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.all
    render inertia: 'Posts/Index', props: {
      posts: jbuilder do |json|
        json.array!(posts) do |post|
          json.extract! post, :id, :content, :created_at
          json.user do
            json.email post.user.email
            json.name post.user.name.familiar
            json.avatar post.user.gravatar_url
          end
        end
      end
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.default_form_builder = TailwindFormBuilder

  def user_gravatar(user, size)
    image_tag(user.gravatar_url, alt: user.name, width: size, height: size, class: 'rounded-full')
  end

  def current_path?(current_path)
    return 'active' if request.path == current_path

    ''
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', defer: true %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="flex flex-row h-full relative">
    <%= render 'shared/sidebar' %>
    <div class="w-full md:w-3/4 pl-24 md:pl-64">
      <%= yield %>
    </div>
    <div class="container bg-gray-200 px-10 md:px-12 py-8 hidden md:flex w-1/4 border-solid border-gray-400 border-l">
      <h1 class="text-2xl">Sidebar</h1>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100">
    <h1 class="logo text-center my-5">
      <%= link_to 'Tweety', unauthenticated_root_path %>
    </h1>
    <div class="bg-white lg:w-4/12 md:6/12 w-10/12 m-auto shadow-md">
      <div class="py-8 px-8 rounded-xl">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar__logo">
    <a href="/" class="logo hidden md:block ml-3">Tweety</a>
    <a href="/" class="block md:hidden text-2xl"><i class="fas fa-kiwi-bird"></i></a>
  </div>
  <nav class="sidebar__nav">
    <div class="flex flex-col items-start">
      <%= link_to authenticated_root_path, class: "sidebar__nav__item #{current_path?(authenticated_root_path)}" do %>
        <i class="fas fa-home"></i>
        <span class="hidden md:inline-block ml-2">Home</span>
      <% end %>
      <a href="/" class="sidebar__nav__item">
        <i class="fas fa-hashtag"></i>
        <span class="hidden md:inline-block ml-2">Explore</span>
      </a>
      <a href="/" class="sidebar__nav__item">
        <i class="fas fa-bell"></i>
        <span class="hidden md:inline-block ml-2">Notifications</span>
      </a>
      <a href="/" class="sidebar__nav__item">
        <i class="fas fa-envelope"></i>
        <span class="hidden md:inline-block ml-2">Messages</span>
      </a>
      <a href="/" class="sidebar__nav__item">
        <i class="fas fa-bookmark"></i>
        <span class="hidden md:inline-block ml-2">Bookmarks</span>
      </a>
      <%= link_to edit_user_registration_path, class: 'sidebar__nav__item' do %>
        <i class="fas fa-user"></i>
        <span class="hidden md:inline-block ml-2">Profile</span>
      <% end %>
    </div>
    <div class="absolute left-0 bottom-0 right-0 p-5">
      <div class="flex flex-row items-center justify-center mb-5">
        <%= user_gravatar(current_user, '30') %>
        <span class="ml-2 hidden md:flex"><%= current_user.name.familiar %></span>
      </div>
      <%= link_to destroy_user_session_path, method: :delete, class: 'sidebar__nav__item' do %>
        <i class="fas fa-sign-out-alt"></i>
        <span class="hidden md:inline-block ml-2">Logout</span>
      <% end %>
      </div>
  </nav>
</div>